sonar.projectKey=websockets
sonar.projectName=websockets
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.inclusions=src/**/*.ts,src/**/*.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/setupTests.ts,src/main.tsx,node_modules/**,dist/**,coverage/**
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.host.url=https://animated-space-goggles-66x4755ww4wc55g5-9000.app.github.dev
# Pass token via env: 
SONAR_TOKEN=sqp_821cb0b341440284e034ae192d519013d9daf625

sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.testExecutionReportPaths=coverage/test-reporter.xml
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8